// Code generated by pigeon; DO NOT EDIT.

package constraint

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Start",
			pos:  position{line: 15, col: 1, offset: 181},
			expr: &actionExpr{
				pos: position{line: 15, col: 10, offset: 190},
				run: (*parser).callonStart1,
				expr: &seqExpr{
					pos: position{line: 15, col: 10, offset: 190},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 15, col: 10, offset: 190},
							label: "types",
							expr: &zeroOrMoreExpr{
								pos: position{line: 15, col: 16, offset: 196},
								expr: &ruleRefExpr{
									pos:  position{line: 15, col: 16, offset: 196},
									name: "TypeDefinition",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 15, col: 32, offset: 212},
							label: "exprs",
							expr: &ruleRefExpr{
								pos:  position{line: 15, col: 38, offset: 218},
								name: "ExpressionList",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 15, col: 53, offset: 233},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "ExpressionList",
			pos:  position{line: 22, col: 1, offset: 342},
			expr: &actionExpr{
				pos: position{line: 22, col: 19, offset: 360},
				run: (*parser).callonExpressionList1,
				expr: &seqExpr{
					pos: position{line: 22, col: 19, offset: 360},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 22, col: 19, offset: 360},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 22, col: 25, offset: 366},
								name: "Expression",
							},
						},
						&labeledExpr{
							pos:   position{line: 22, col: 36, offset: 377},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 22, col: 41, offset: 382},
								expr: &seqExpr{
									pos: position{line: 22, col: 42, offset: 383},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 22, col: 42, offset: 383},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 22, col: 44, offset: 385},
											name: "Expression",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "TypeDefinition",
			pos:  position{line: 32, col: 1, offset: 631},
			expr: &actionExpr{
				pos: position{line: 32, col: 19, offset: 649},
				run: (*parser).callonTypeDefinition1,
				expr: &seqExpr{
					pos: position{line: 32, col: 19, offset: 649},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 32, col: 19, offset: 649},
							val:        "type",
							ignoreCase: false,
							want:       "\"type\"",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 26, offset: 656},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 32, col: 28, offset: 658},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 33, offset: 663},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 44, offset: 674},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 32, col: 46, offset: 676},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 50, offset: 680},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 32, col: 52, offset: 682},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 56, offset: 686},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 32, col: 58, offset: 688},
							label: "fields",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 65, offset: 695},
								name: "FieldList",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 75, offset: 705},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 32, col: 77, offset: 707},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 81, offset: 711},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "FieldList",
			pos:  position{line: 40, col: 1, offset: 846},
			expr: &actionExpr{
				pos: position{line: 40, col: 14, offset: 859},
				run: (*parser).callonFieldList1,
				expr: &seqExpr{
					pos: position{line: 40, col: 14, offset: 859},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 40, col: 14, offset: 859},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 20, offset: 865},
								name: "Field",
							},
						},
						&labeledExpr{
							pos:   position{line: 40, col: 26, offset: 871},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 40, col: 31, offset: 876},
								expr: &seqExpr{
									pos: position{line: 40, col: 32, offset: 877},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 40, col: 32, offset: 877},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 40, col: 34, offset: 879},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 38, offset: 883},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 40, offset: 885},
											name: "Field",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 50, col: 1, offset: 1106},
			expr: &actionExpr{
				pos: position{line: 50, col: 10, offset: 1115},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 50, col: 10, offset: 1115},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 50, col: 10, offset: 1115},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 15, offset: 1120},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 26, offset: 1131},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 50, col: 28, offset: 1133},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 32, offset: 1137},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 50, col: 34, offset: 1139},
							label: "fieldType",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 44, offset: 1149},
								name: "AtomicType",
							},
						},
					},
				},
			},
		},
		{
			name: "AtomicType",
			pos:  position{line: 57, col: 1, offset: 1260},
			expr: &choiceExpr{
				pos: position{line: 57, col: 15, offset: 1274},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 57, col: 15, offset: 1274},
						run: (*parser).callonAtomicType2,
						expr: &litMatcher{
							pos:        position{line: 57, col: 15, offset: 1274},
							val:        "string",
							ignoreCase: false,
							want:       "\"string\"",
						},
					},
					&actionExpr{
						pos: position{line: 58, col: 15, offset: 1324},
						run: (*parser).callonAtomicType4,
						expr: &litMatcher{
							pos:        position{line: 58, col: 15, offset: 1324},
							val:        "number",
							ignoreCase: false,
							want:       "\"number\"",
						},
					},
					&actionExpr{
						pos: position{line: 59, col: 15, offset: 1374},
						run: (*parser).callonAtomicType6,
						expr: &litMatcher{
							pos:        position{line: 59, col: 15, offset: 1374},
							val:        "bool",
							ignoreCase: false,
							want:       "\"bool\"",
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 61, col: 1, offset: 1407},
			expr: &actionExpr{
				pos: position{line: 61, col: 15, offset: 1421},
				run: (*parser).callonExpression1,
				expr: &seqExpr{
					pos: position{line: 61, col: 15, offset: 1421},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 61, col: 15, offset: 1421},
							label: "set",
							expr: &ruleRefExpr{
								pos:  position{line: 61, col: 19, offset: 1425},
								name: "Set",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 61, col: 23, offset: 1429},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 61, col: 25, offset: 1431},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&ruleRefExpr{
							pos:  position{line: 61, col: 29, offset: 1435},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 61, col: 31, offset: 1437},
							label: "constraints",
							expr: &ruleRefExpr{
								pos:  position{line: 61, col: 43, offset: 1449},
								name: "Constraints",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 61, col: 55, offset: 1461},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 61, col: 57, offset: 1463},
							label: "action",
							expr: &zeroOrOneExpr{
								pos: position{line: 61, col: 64, offset: 1470},
								expr: &ruleRefExpr{
									pos:  position{line: 61, col: 64, offset: 1470},
									name: "Action",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Set",
			pos:  position{line: 73, col: 1, offset: 1693},
			expr: &actionExpr{
				pos: position{line: 73, col: 8, offset: 1700},
				run: (*parser).callonSet1,
				expr: &seqExpr{
					pos: position{line: 73, col: 8, offset: 1700},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 73, col: 8, offset: 1700},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 73, col: 12, offset: 1704},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 73, col: 14, offset: 1706},
							label: "variables",
							expr: &ruleRefExpr{
								pos:  position{line: 73, col: 24, offset: 1716},
								name: "TypedVariableList",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 73, col: 42, offset: 1734},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 73, col: 44, offset: 1736},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "TypedVariableList",
			pos:  position{line: 80, col: 1, offset: 1846},
			expr: &actionExpr{
				pos: position{line: 80, col: 22, offset: 1867},
				run: (*parser).callonTypedVariableList1,
				expr: &seqExpr{
					pos: position{line: 80, col: 22, offset: 1867},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 80, col: 22, offset: 1867},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 80, col: 28, offset: 1873},
								name: "TypedVariable",
							},
						},
						&labeledExpr{
							pos:   position{line: 80, col: 42, offset: 1887},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 80, col: 47, offset: 1892},
								expr: &seqExpr{
									pos: position{line: 80, col: 48, offset: 1893},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 80, col: 48, offset: 1893},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 80, col: 50, offset: 1895},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 80, col: 54, offset: 1899},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 80, col: 56, offset: 1901},
											name: "TypedVariable",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "TypedVariable",
			pos:  position{line: 90, col: 1, offset: 2142},
			expr: &actionExpr{
				pos: position{line: 90, col: 18, offset: 2159},
				run: (*parser).callonTypedVariable1,
				expr: &seqExpr{
					pos: position{line: 90, col: 18, offset: 2159},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 90, col: 18, offset: 2159},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 90, col: 23, offset: 2164},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 90, col: 34, offset: 2175},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 90, col: 36, offset: 2177},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 90, col: 40, offset: 2181},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 90, col: 42, offset: 2183},
							label: "dataType",
							expr: &ruleRefExpr{
								pos:  position{line: 90, col: 51, offset: 2192},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Constraints",
			pos:  position{line: 98, col: 1, offset: 2339},
			expr: &actionExpr{
				pos: position{line: 98, col: 16, offset: 2354},
				run: (*parser).callonConstraints1,
				expr: &seqExpr{
					pos: position{line: 98, col: 16, offset: 2354},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 98, col: 16, offset: 2354},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 22, offset: 2360},
								name: "Constraint",
							},
						},
						&labeledExpr{
							pos:   position{line: 98, col: 33, offset: 2371},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 98, col: 38, offset: 2376},
								expr: &seqExpr{
									pos: position{line: 98, col: 39, offset: 2377},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 98, col: 39, offset: 2377},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 98, col: 41, offset: 2379},
											name: "LogicalOp",
										},
										&ruleRefExpr{
											pos:  position{line: 98, col: 51, offset: 2389},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 98, col: 53, offset: 2391},
											name: "Constraint",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Constraint",
			pos:  position{line: 120, col: 1, offset: 2943},
			expr: &choiceExpr{
				pos: position{line: 120, col: 15, offset: 2957},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 120, col: 15, offset: 2957},
						run: (*parser).callonConstraint2,
						expr: &seqExpr{
							pos: position{line: 120, col: 15, offset: 2957},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 120, col: 15, offset: 2957},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 120, col: 19, offset: 2961},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 120, col: 21, offset: 2963},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 120, col: 26, offset: 2968},
										name: "Constraints",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 120, col: 38, offset: 2980},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 120, col: 40, offset: 2982},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 121, col: 15, offset: 3023},
						run: (*parser).callonConstraint10,
						expr: &seqExpr{
							pos: position{line: 121, col: 15, offset: 3023},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 121, col: 15, offset: 3023},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 20, offset: 3028},
										name: "ArithmeticExpr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 35, offset: 3043},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 121, col: 37, offset: 3045},
									label: "op",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 40, offset: 3048},
										name: "ComparisonOp",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 53, offset: 3061},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 121, col: 55, offset: 3063},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 61, offset: 3069},
										name: "ArithmeticExpr",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ArithmeticExpr",
			pos:  position{line: 130, col: 1, offset: 3235},
			expr: &actionExpr{
				pos: position{line: 130, col: 19, offset: 3253},
				run: (*parser).callonArithmeticExpr1,
				expr: &seqExpr{
					pos: position{line: 130, col: 19, offset: 3253},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 130, col: 19, offset: 3253},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 130, col: 25, offset: 3259},
								name: "Term",
							},
						},
						&labeledExpr{
							pos:   position{line: 130, col: 30, offset: 3264},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 130, col: 35, offset: 3269},
								expr: &seqExpr{
									pos: position{line: 130, col: 36, offset: 3270},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 130, col: 36, offset: 3270},
											name: "_",
										},
										&choiceExpr{
											pos: position{line: 130, col: 39, offset: 3273},
											alternatives: []any{
												&litMatcher{
													pos:        position{line: 130, col: 39, offset: 3273},
													val:        "+",
													ignoreCase: false,
													want:       "\"+\"",
												},
												&litMatcher{
													pos:        position{line: 130, col: 45, offset: 3279},
													val:        "-",
													ignoreCase: false,
													want:       "\"-\"",
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 130, col: 50, offset: 3284},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 130, col: 52, offset: 3286},
											name: "Term",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Term",
			pos:  position{line: 149, col: 1, offset: 3733},
			expr: &actionExpr{
				pos: position{line: 149, col: 9, offset: 3741},
				run: (*parser).callonTerm1,
				expr: &seqExpr{
					pos: position{line: 149, col: 9, offset: 3741},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 149, col: 9, offset: 3741},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 149, col: 15, offset: 3747},
								name: "Factor",
							},
						},
						&labeledExpr{
							pos:   position{line: 149, col: 22, offset: 3754},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 149, col: 27, offset: 3759},
								expr: &seqExpr{
									pos: position{line: 149, col: 28, offset: 3760},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 149, col: 28, offset: 3760},
											name: "_",
										},
										&choiceExpr{
											pos: position{line: 149, col: 31, offset: 3763},
											alternatives: []any{
												&litMatcher{
													pos:        position{line: 149, col: 31, offset: 3763},
													val:        "*",
													ignoreCase: false,
													want:       "\"*\"",
												},
												&litMatcher{
													pos:        position{line: 149, col: 37, offset: 3769},
													val:        "/",
													ignoreCase: false,
													want:       "\"/\"",
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 149, col: 42, offset: 3774},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 149, col: 44, offset: 3776},
											name: "Factor",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Factor",
			pos:  position{line: 168, col: 1, offset: 4225},
			expr: &choiceExpr{
				pos: position{line: 168, col: 11, offset: 4235},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 168, col: 11, offset: 4235},
						run: (*parser).callonFactor2,
						expr: &seqExpr{
							pos: position{line: 168, col: 11, offset: 4235},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 168, col: 11, offset: 4235},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 168, col: 15, offset: 4239},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 168, col: 17, offset: 4241},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 168, col: 22, offset: 4246},
										name: "ArithmeticExpr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 168, col: 37, offset: 4261},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 168, col: 39, offset: 4263},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 169, col: 11, offset: 4300},
						name: "FieldAccess",
					},
					&ruleRefExpr{
						pos:  position{line: 170, col: 11, offset: 4324},
						name: "Variable",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 11, offset: 4345},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 172, col: 11, offset: 4364},
						name: "StringLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 173, col: 11, offset: 4390},
						name: "BooleanLiteral",
					},
				},
			},
		},
		{
			name: "FieldAccess",
			pos:  position{line: 175, col: 1, offset: 4406},
			expr: &actionExpr{
				pos: position{line: 175, col: 16, offset: 4421},
				run: (*parser).callonFieldAccess1,
				expr: &seqExpr{
					pos: position{line: 175, col: 16, offset: 4421},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 175, col: 16, offset: 4421},
							label: "object",
							expr: &ruleRefExpr{
								pos:  position{line: 175, col: 23, offset: 4428},
								name: "Identifier",
							},
						},
						&litMatcher{
							pos:        position{line: 175, col: 34, offset: 4439},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 175, col: 38, offset: 4443},
							label: "field",
							expr: &ruleRefExpr{
								pos:  position{line: 175, col: 44, offset: 4449},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Variable",
			pos:  position{line: 183, col: 1, offset: 4592},
			expr: &actionExpr{
				pos: position{line: 183, col: 13, offset: 4604},
				run: (*parser).callonVariable1,
				expr: &labeledExpr{
					pos:   position{line: 183, col: 13, offset: 4604},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 183, col: 18, offset: 4609},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "ComparisonOp",
			pos:  position{line: 190, col: 1, offset: 4721},
			expr: &choiceExpr{
				pos: position{line: 190, col: 17, offset: 4737},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 190, col: 17, offset: 4737},
						run: (*parser).callonComparisonOp2,
						expr: &litMatcher{
							pos:        position{line: 190, col: 17, offset: 4737},
							val:        "==",
							ignoreCase: false,
							want:       "\"==\"",
						},
					},
					&actionExpr{
						pos: position{line: 191, col: 17, offset: 4781},
						run: (*parser).callonComparisonOp4,
						expr: &litMatcher{
							pos:        position{line: 191, col: 17, offset: 4781},
							val:        "!=",
							ignoreCase: false,
							want:       "\"!=\"",
						},
					},
					&actionExpr{
						pos: position{line: 192, col: 17, offset: 4825},
						run: (*parser).callonComparisonOp6,
						expr: &litMatcher{
							pos:        position{line: 192, col: 17, offset: 4825},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
					},
					&actionExpr{
						pos: position{line: 193, col: 17, offset: 4869},
						run: (*parser).callonComparisonOp8,
						expr: &litMatcher{
							pos:        position{line: 193, col: 17, offset: 4869},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
					},
					&actionExpr{
						pos: position{line: 194, col: 17, offset: 4913},
						run: (*parser).callonComparisonOp10,
						expr: &litMatcher{
							pos:        position{line: 194, col: 17, offset: 4913},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
					},
					&actionExpr{
						pos: position{line: 195, col: 17, offset: 4956},
						run: (*parser).callonComparisonOp12,
						expr: &litMatcher{
							pos:        position{line: 195, col: 17, offset: 4956},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
					},
					&actionExpr{
						pos: position{line: 196, col: 17, offset: 4999},
						run: (*parser).callonComparisonOp14,
						expr: &litMatcher{
							pos:        position{line: 196, col: 17, offset: 4999},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
					},
				},
			},
		},
		{
			name: "LogicalOp",
			pos:  position{line: 198, col: 1, offset: 5025},
			expr: &choiceExpr{
				pos: position{line: 198, col: 14, offset: 5038},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 198, col: 14, offset: 5038},
						run: (*parser).callonLogicalOp2,
						expr: &litMatcher{
							pos:        position{line: 198, col: 14, offset: 5038},
							val:        "AND",
							ignoreCase: false,
							want:       "\"AND\"",
						},
					},
					&actionExpr{
						pos: position{line: 199, col: 14, offset: 5081},
						run: (*parser).callonLogicalOp4,
						expr: &litMatcher{
							pos:        position{line: 199, col: 14, offset: 5081},
							val:        "OR",
							ignoreCase: false,
							want:       "\"OR\"",
						},
					},
					&actionExpr{
						pos: position{line: 200, col: 14, offset: 5123},
						run: (*parser).callonLogicalOp6,
						expr: &litMatcher{
							pos:        position{line: 200, col: 14, offset: 5123},
							val:        "&&",
							ignoreCase: false,
							want:       "\"&&\"",
						},
					},
					&actionExpr{
						pos: position{line: 201, col: 14, offset: 5165},
						run: (*parser).callonLogicalOp8,
						expr: &litMatcher{
							pos:        position{line: 201, col: 14, offset: 5165},
							val:        "||",
							ignoreCase: false,
							want:       "\"||\"",
						},
					},
					&actionExpr{
						pos: position{line: 202, col: 14, offset: 5207},
						run: (*parser).callonLogicalOp10,
						expr: &litMatcher{
							pos:        position{line: 202, col: 14, offset: 5207},
							val:        "&",
							ignoreCase: false,
							want:       "\"&\"",
						},
					},
					&actionExpr{
						pos: position{line: 203, col: 14, offset: 5248},
						run: (*parser).callonLogicalOp12,
						expr: &litMatcher{
							pos:        position{line: 203, col: 14, offset: 5248},
							val:        "|",
							ignoreCase: false,
							want:       "\"|\"",
						},
					},
				},
			},
		},
		{
			name: "Action",
			pos:  position{line: 205, col: 1, offset: 5275},
			expr: &actionExpr{
				pos: position{line: 205, col: 11, offset: 5285},
				run: (*parser).callonAction1,
				expr: &seqExpr{
					pos: position{line: 205, col: 11, offset: 5285},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 205, col: 11, offset: 5285},
							val:        "==>",
							ignoreCase: false,
							want:       "\"==>\"",
						},
						&ruleRefExpr{
							pos:  position{line: 205, col: 17, offset: 5291},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 205, col: 19, offset: 5293},
							label: "job",
							expr: &ruleRefExpr{
								pos:  position{line: 205, col: 23, offset: 5297},
								name: "JobCall",
							},
						},
					},
				},
			},
		},
		{
			name: "JobCall",
			pos:  position{line: 212, col: 1, offset: 5402},
			expr: &actionExpr{
				pos: position{line: 212, col: 12, offset: 5413},
				run: (*parser).callonJobCall1,
				expr: &seqExpr{
					pos: position{line: 212, col: 12, offset: 5413},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 212, col: 12, offset: 5413},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 212, col: 17, offset: 5418},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 212, col: 28, offset: 5429},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 212, col: 30, offset: 5431},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 212, col: 34, offset: 5435},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 212, col: 36, offset: 5437},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 212, col: 41, offset: 5442},
								expr: &ruleRefExpr{
									pos:  position{line: 212, col: 41, offset: 5442},
									name: "ArgumentList",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 212, col: 55, offset: 5456},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 212, col: 57, offset: 5458},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "ArgumentList",
			pos:  position{line: 223, col: 1, offset: 5642},
			expr: &actionExpr{
				pos: position{line: 223, col: 17, offset: 5658},
				run: (*parser).callonArgumentList1,
				expr: &seqExpr{
					pos: position{line: 223, col: 17, offset: 5658},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 223, col: 17, offset: 5658},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 223, col: 23, offset: 5664},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 223, col: 34, offset: 5675},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 223, col: 39, offset: 5680},
								expr: &seqExpr{
									pos: position{line: 223, col: 40, offset: 5681},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 223, col: 40, offset: 5681},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 223, col: 42, offset: 5683},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 223, col: 46, offset: 5687},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 223, col: 48, offset: 5689},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BooleanLiteral",
			pos:  position{line: 233, col: 1, offset: 5927},
			expr: &choiceExpr{
				pos: position{line: 233, col: 19, offset: 5945},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 233, col: 19, offset: 5945},
						run: (*parser).callonBooleanLiteral2,
						expr: &litMatcher{
							pos:        position{line: 233, col: 19, offset: 5945},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 239, col: 5, offset: 6082},
						run: (*parser).callonBooleanLiteral4,
						expr: &litMatcher{
							pos:        position{line: 239, col: 5, offset: 6082},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 246, col: 1, offset: 6215},
			expr: &actionExpr{
				pos: position{line: 246, col: 11, offset: 6225},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 246, col: 11, offset: 6225},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 246, col: 11, offset: 6225},
							expr: &charClassMatcher{
								pos:        position{line: 246, col: 11, offset: 6225},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 246, col: 18, offset: 6232},
							expr: &seqExpr{
								pos: position{line: 246, col: 19, offset: 6233},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 246, col: 19, offset: 6233},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 246, col: 23, offset: 6237},
										expr: &charClassMatcher{
											pos:        position{line: 246, col: 23, offset: 6237},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 257, col: 1, offset: 6450},
			expr: &choiceExpr{
				pos: position{line: 257, col: 18, offset: 6467},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 257, col: 18, offset: 6467},
						run: (*parser).callonStringLiteral2,
						expr: &seqExpr{
							pos: position{line: 257, col: 18, offset: 6467},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 257, col: 18, offset: 6467},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&labeledExpr{
									pos:   position{line: 257, col: 23, offset: 6472},
									label: "chars",
									expr: &zeroOrMoreExpr{
										pos: position{line: 257, col: 29, offset: 6478},
										expr: &ruleRefExpr{
											pos:  position{line: 257, col: 29, offset: 6478},
											name: "DoubleStringChar",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 257, col: 47, offset: 6496},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 263, col: 5, offset: 6656},
						run: (*parser).callonStringLiteral9,
						expr: &seqExpr{
							pos: position{line: 263, col: 5, offset: 6656},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 263, col: 5, offset: 6656},
									val:        "'",
									ignoreCase: false,
									want:       "\"'\"",
								},
								&labeledExpr{
									pos:   position{line: 263, col: 9, offset: 6660},
									label: "chars",
									expr: &zeroOrMoreExpr{
										pos: position{line: 263, col: 15, offset: 6666},
										expr: &ruleRefExpr{
											pos:  position{line: 263, col: 15, offset: 6666},
											name: "SingleStringChar",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 263, col: 33, offset: 6684},
									val:        "'",
									ignoreCase: false,
									want:       "\"'\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleStringChar",
			pos:  position{line: 270, col: 1, offset: 6839},
			expr: &actionExpr{
				pos: position{line: 270, col: 21, offset: 6859},
				run: (*parser).callonDoubleStringChar1,
				expr: &seqExpr{
					pos: position{line: 270, col: 21, offset: 6859},
					exprs: []any{
						&notExpr{
							pos: position{line: 270, col: 21, offset: 6859},
							expr: &litMatcher{
								pos:        position{line: 270, col: 22, offset: 6860},
								val:        "\"",
								ignoreCase: false,
								want:       "\"\\\"\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 270, col: 26, offset: 6864},
							label: "char",
							expr: &anyMatcher{
								line: 270, col: 31, offset: 6869,
							},
						},
					},
				},
			},
		},
		{
			name: "SingleStringChar",
			pos:  position{line: 272, col: 1, offset: 6910},
			expr: &actionExpr{
				pos: position{line: 272, col: 21, offset: 6930},
				run: (*parser).callonSingleStringChar1,
				expr: &seqExpr{
					pos: position{line: 272, col: 21, offset: 6930},
					exprs: []any{
						&notExpr{
							pos: position{line: 272, col: 21, offset: 6930},
							expr: &litMatcher{
								pos:        position{line: 272, col: 22, offset: 6931},
								val:        "'",
								ignoreCase: false,
								want:       "\"'\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 272, col: 27, offset: 6936},
							label: "char",
							expr: &anyMatcher{
								line: 272, col: 32, offset: 6941,
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 274, col: 1, offset: 6982},
			expr: &actionExpr{
				pos: position{line: 274, col: 15, offset: 6996},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 274, col: 15, offset: 6996},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 274, col: 15, offset: 6996},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 274, col: 23, offset: 7004},
							expr: &charClassMatcher{
								pos:        position{line: 274, col: 23, offset: 7004},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 278, col: 1, offset: 7054},
			expr: &choiceExpr{
				pos: position{line: 278, col: 6, offset: 7059},
				alternatives: []any{
					&zeroOrMoreExpr{
						pos: position{line: 278, col: 6, offset: 7059},
						expr: &charClassMatcher{
							pos:        position{line: 278, col: 6, offset: 7059},
							val:        "[ \\t\\r\\n]",
							chars:      []rune{' ', '\t', '\r', '\n'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 278, col: 19, offset: 7072},
						expr: &ruleRefExpr{
							pos:  position{line: 278, col: 19, offset: 7072},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 280, col: 1, offset: 7082},
			expr: &choiceExpr{
				pos: position{line: 280, col: 12, offset: 7093},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 280, col: 12, offset: 7093},
						exprs: []any{
							&litMatcher{
								pos:        position{line: 280, col: 12, offset: 7093},
								val:        "//",
								ignoreCase: false,
								want:       "\"//\"",
							},
							&zeroOrMoreExpr{
								pos: position{line: 280, col: 17, offset: 7098},
								expr: &charClassMatcher{
									pos:        position{line: 280, col: 17, offset: 7098},
									val:        "[^\\r\\n]",
									chars:      []rune{'\r', '\n'},
									ignoreCase: false,
									inverted:   true,
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 281, col: 12, offset: 7120},
						exprs: []any{
							&litMatcher{
								pos:        position{line: 281, col: 12, offset: 7120},
								val:        "/*",
								ignoreCase: false,
								want:       "\"/*\"",
							},
							&zeroOrMoreExpr{
								pos: position{line: 281, col: 17, offset: 7125},
								expr: &seqExpr{
									pos: position{line: 281, col: 18, offset: 7126},
									exprs: []any{
										&notExpr{
											pos: position{line: 281, col: 18, offset: 7126},
											expr: &litMatcher{
												pos:        position{line: 281, col: 19, offset: 7127},
												val:        "*/",
												ignoreCase: false,
												want:       "\"*/\"",
											},
										},
										&anyMatcher{
											line: 281, col: 24, offset: 7132,
										},
									},
								},
							},
							&litMatcher{
								pos:        position{line: 281, col: 28, offset: 7136},
								val:        "*/",
								ignoreCase: false,
								want:       "\"*/\"",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 283, col: 1, offset: 7142},
			expr: &notExpr{
				pos: position{line: 283, col: 8, offset: 7149},
				expr: &anyMatcher{
					line: 283, col: 9, offset: 7150,
				},
			},
		},
	},
}

func (c *current) onStart1(types, exprs any) (any, error) {
	return map[string]interface{}{
		"types":       types,
		"expressions": exprs,
	}, nil
}

func (p *parser) callonStart1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStart1(stack["types"], stack["exprs"])
}

func (c *current) onExpressionList1(first, rest any) (any, error) {
	expressions := []interface{}{first}
	if rest != nil {
		for _, item := range rest.([]interface{}) {
			expressions = append(expressions, item.([]interface{})[1])
		}
	}
	return expressions, nil
}

func (p *parser) callonExpressionList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionList1(stack["first"], stack["rest"])
}

func (c *current) onTypeDefinition1(name, fields any) (any, error) {
	return map[string]interface{}{
		"type":   "typeDefinition",
		"name":   name,
		"fields": fields,
	}, nil
}

func (p *parser) callonTypeDefinition1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeDefinition1(stack["name"], stack["fields"])
}

func (c *current) onFieldList1(first, rest any) (any, error) {
	fields := []interface{}{first}
	if rest != nil {
		for _, item := range rest.([]interface{}) {
			fields = append(fields, item.([]interface{})[3])
		}
	}
	return fields, nil
}

func (p *parser) callonFieldList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldList1(stack["first"], stack["rest"])
}

func (c *current) onField1(name, fieldType any) (any, error) {
	return map[string]interface{}{
		"name": name,
		"type": fieldType,
	}, nil
}

func (p *parser) callonField1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["name"], stack["fieldType"])
}

func (c *current) onAtomicType2() (any, error) {
	return "string", nil
}

func (p *parser) callonAtomicType2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtomicType2()
}

func (c *current) onAtomicType4() (any, error) {
	return "number", nil
}

func (p *parser) callonAtomicType4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtomicType4()
}

func (c *current) onAtomicType6() (any, error) {
	return "bool", nil
}

func (p *parser) callonAtomicType6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtomicType6()
}

func (c *current) onExpression1(set, constraints, action any) (any, error) {
	expr := map[string]interface{}{
		"type":        "expression",
		"set":         set,
		"constraints": constraints,
	}
	if action != nil {
		expr["action"] = action
	}
	return expr, nil
}

func (p *parser) callonExpression1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression1(stack["set"], stack["constraints"], stack["action"])
}

func (c *current) onSet1(variables any) (any, error) {
	return map[string]interface{}{
		"type":      "set",
		"variables": variables,
	}, nil
}

func (p *parser) callonSet1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSet1(stack["variables"])
}

func (c *current) onTypedVariableList1(first, rest any) (any, error) {
	variables := []interface{}{first}
	if rest != nil {
		for _, item := range rest.([]interface{}) {
			variables = append(variables, item.([]interface{})[3])
		}
	}
	return variables, nil
}

func (p *parser) callonTypedVariableList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypedVariableList1(stack["first"], stack["rest"])
}

func (c *current) onTypedVariable1(name, dataType any) (any, error) {
	return map[string]interface{}{
		"type":     "typedVariable",
		"name":     name,
		"dataType": dataType,
	}, nil
}

func (p *parser) callonTypedVariable1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypedVariable1(stack["name"], stack["dataType"])
}

func (c *current) onConstraints1(first, rest any) (any, error) {
	if rest == nil || len(rest.([]interface{})) == 0 {
		return first, nil
	}

	operations := []map[string]interface{}{}
	for _, item := range rest.([]interface{}) {
		op := item.([]interface{})[1]
		right := item.([]interface{})[3]
		operations = append(operations, map[string]interface{}{
			"op":    op,
			"right": right,
		})
	}

	return map[string]interface{}{
		"type":       "logicalExpr",
		"left":       first,
		"operations": operations,
	}, nil
}

func (p *parser) callonConstraints1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstraints1(stack["first"], stack["rest"])
}

func (c *current) onConstraint2(expr any) (any, error) {
	return expr, nil
}

func (p *parser) callonConstraint2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstraint2(stack["expr"])
}

func (c *current) onConstraint10(left, op, right any) (any, error) {
	return map[string]interface{}{
		"type":     "comparison",
		"left":     left,
		"operator": op,
		"right":    right,
	}, nil
}

func (p *parser) callonConstraint10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstraint10(stack["left"], stack["op"], stack["right"])
}

func (c *current) onArithmeticExpr1(first, rest any) (any, error) {
	if rest == nil || len(rest.([]interface{})) == 0 {
		return first, nil
	}

	result := first
	for _, item := range rest.([]interface{}) {
		op := item.([]interface{})[1]
		right := item.([]interface{})[3]
		result = map[string]interface{}{
			"type":     "binaryOp",
			"left":     result,
			"operator": op,
			"right":    right,
		}
	}
	return result, nil
}

func (p *parser) callonArithmeticExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArithmeticExpr1(stack["first"], stack["rest"])
}

func (c *current) onTerm1(first, rest any) (any, error) {
	if rest == nil || len(rest.([]interface{})) == 0 {
		return first, nil
	}

	result := first
	for _, item := range rest.([]interface{}) {
		op := item.([]interface{})[1]
		right := item.([]interface{})[3]
		result = map[string]interface{}{
			"type":     "binaryOp",
			"left":     result,
			"operator": op,
			"right":    right,
		}
	}
	return result, nil
}

func (p *parser) callonTerm1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTerm1(stack["first"], stack["rest"])
}

func (c *current) onFactor2(expr any) (any, error) {
	return expr, nil
}

func (p *parser) callonFactor2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor2(stack["expr"])
}

func (c *current) onFieldAccess1(object, field any) (any, error) {
	return map[string]interface{}{
		"type":   "fieldAccess",
		"object": object,
		"field":  field,
	}, nil
}

func (p *parser) callonFieldAccess1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldAccess1(stack["object"], stack["field"])
}

func (c *current) onVariable1(name any) (any, error) {
	return map[string]interface{}{
		"type": "variable",
		"name": name,
	}, nil
}

func (p *parser) callonVariable1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable1(stack["name"])
}

func (c *current) onComparisonOp2() (any, error) {
	return "==", nil
}

func (p *parser) callonComparisonOp2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonOp2()
}

func (c *current) onComparisonOp4() (any, error) {
	return "!=", nil
}

func (p *parser) callonComparisonOp4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonOp4()
}

func (c *current) onComparisonOp6() (any, error) {
	return "<=", nil
}

func (p *parser) callonComparisonOp6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonOp6()
}

func (c *current) onComparisonOp8() (any, error) {
	return ">=", nil
}

func (p *parser) callonComparisonOp8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonOp8()
}

func (c *current) onComparisonOp10() (any, error) {
	return "=", nil
}

func (p *parser) callonComparisonOp10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonOp10()
}

func (c *current) onComparisonOp12() (any, error) {
	return "<", nil
}

func (p *parser) callonComparisonOp12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonOp12()
}

func (c *current) onComparisonOp14() (any, error) {
	return ">", nil
}

func (p *parser) callonComparisonOp14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonOp14()
}

func (c *current) onLogicalOp2() (any, error) {
	return "AND", nil
}

func (p *parser) callonLogicalOp2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalOp2()
}

func (c *current) onLogicalOp4() (any, error) {
	return "OR", nil
}

func (p *parser) callonLogicalOp4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalOp4()
}

func (c *current) onLogicalOp6() (any, error) {
	return "&&", nil
}

func (p *parser) callonLogicalOp6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalOp6()
}

func (c *current) onLogicalOp8() (any, error) {
	return "||", nil
}

func (p *parser) callonLogicalOp8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalOp8()
}

func (c *current) onLogicalOp10() (any, error) {
	return "&", nil
}

func (p *parser) callonLogicalOp10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalOp10()
}

func (c *current) onLogicalOp12() (any, error) {
	return "|", nil
}

func (p *parser) callonLogicalOp12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalOp12()
}

func (c *current) onAction1(job any) (any, error) {
	return map[string]interface{}{
		"type": "action",
		"job":  job,
	}, nil
}

func (p *parser) callonAction1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAction1(stack["job"])
}

func (c *current) onJobCall1(name, args any) (any, error) {
	if args == nil {
		args = []interface{}{}
	}
	return map[string]interface{}{
		"type": "jobCall",
		"name": name,
		"args": args,
	}, nil
}

func (p *parser) callonJobCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJobCall1(stack["name"], stack["args"])
}

func (c *current) onArgumentList1(first, rest any) (any, error) {
	arguments := []interface{}{first}
	if rest != nil {
		for _, item := range rest.([]interface{}) {
			arguments = append(arguments, item.([]interface{})[3])
		}
	}
	return arguments, nil
}

func (p *parser) callonArgumentList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgumentList1(stack["first"], stack["rest"])
}

func (c *current) onBooleanLiteral2() (any, error) {

	return map[string]interface{}{
		"type":  "boolean",
		"value": true,
	}, nil

}

func (p *parser) callonBooleanLiteral2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBooleanLiteral2()
}

func (c *current) onBooleanLiteral4() (any, error) {

	return map[string]interface{}{
		"type":  "boolean",
		"value": false,
	}, nil

}

func (p *parser) callonBooleanLiteral4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBooleanLiteral4()
}

func (c *current) onNumber1() (any, error) {
	val, err := strconv.ParseFloat(string(c.text), 64)
	if err != nil {
		return nil, err
	}
	return map[string]interface{}{
		"type":  "number",
		"value": val,
	}, nil
}

func (p *parser) callonNumber1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onStringLiteral2(chars any) (any, error) {
	return map[string]interface{}{
		"type":  "string",
		"value": strings.Join(chars.([]string), ""),
	}, nil

}

func (p *parser) callonStringLiteral2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral2(stack["chars"])
}

func (c *current) onStringLiteral9(chars any) (any, error) {
	return map[string]interface{}{
		"type":  "string",
		"value": strings.Join(chars.([]string), ""),
	}, nil

}

func (p *parser) callonStringLiteral9() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral9(stack["chars"])
}

func (c *current) onDoubleStringChar1(char any) (any, error) {
	return string(char.([]byte)), nil
}

func (p *parser) callonDoubleStringChar1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleStringChar1(stack["char"])
}

func (c *current) onSingleStringChar1(char any) (any, error) {
	return string(char.([]byte)), nil
}

func (p *parser) callonSingleStringChar1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleStringChar1(stack["char"])
}

func (c *current) onIdentifier1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
